In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(f"Shape of x_data is: {x_data.shape}")

Shape of x_data is: torch.Size([2, 2])


In [8]:
#np.random.normal(10,100, [100,10])
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9316, 0.1774],
        [0.4831, 0.4107]]) 



In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
torch.cat([tensor, tensor, tensor])

tensor([[0.8061, 0.3613, 0.4342, 0.2329],
        [0.9348, 0.3914, 0.1998, 0.1319],
        [0.1103, 0.5306, 0.8771, 0.5599],
        [0.8061, 0.3613, 0.4342, 0.2329],
        [0.9348, 0.3914, 0.1998, 0.1319],
        [0.1103, 0.5306, 0.8771, 0.5599],
        [0.8061, 0.3613, 0.4342, 0.2329],
        [0.9348, 0.3914, 0.1998, 0.1319],
        [0.1103, 0.5306, 0.8771, 0.5599]])

In [22]:
tensor

tensor([[0.8061, 0.3613, 0.4342, 0.2329],
        [0.9348, 0.3914, 0.1998, 0.1319],
        [0.1103, 0.5306, 0.8771, 0.5599]])

In [23]:
tensor_2 = torch.rand([3,5])

In [26]:
torch.cat([tensor, tensor, tensor,tensor_2],dim = 1).shape

torch.Size([3, 17])

In [27]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [28]:
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.0232, 1.0125, 0.7919],
        [1.0125, 1.0844, 0.5599],
        [0.7919, 0.5599, 1.3765]])

In [31]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
