In [3]:
import torch
torch.backends.mps.is_available()

True

In [4]:
a = torch.rand((2,3))

In [7]:
a

tensor([[0.6128, 0.8796, 0.5494],
        [0.8022, 0.9192, 0.8213]])

In [12]:
torch.einsum('ij->j', a)

tensor([1.4150, 1.7988, 1.3708])

In [18]:
torch.einsum('i->i1', a[0])

RuntimeError: einsum(): invalid subscript given at index 4 in the equation string, subscripts must be in [a-zA-Z]

In [20]:
import torch

a = torch.tensor([1, 2, 3])  # Example 1D vector
column_vector = torch.einsum('i->i,j', a, torch.ones(1))
print(column_vector)


RuntimeError: einsum(): more operands were provided than specified in the equation

In [21]:
import torch.nn as nn

In [23]:
softmax_f = nn.Softmax(dim=-1)
a = torch.rand((10,3))
a_softmax = softmax_f(a)

In [27]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])
input_tensor.shape

torch.Size([1, 8])

In [28]:
model = nn.Sequential(
    nn.Linear(8,1),
    nn.Sigmoid()
)
output = model(input_tensor)
print(output)

tensor([[0.7389]], grad_fn=<SigmoidBackward0>)


In [29]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])
input_tensor.shape

torch.Size([1, 11])

In [32]:
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss

In [33]:
F.one_hot(torch.tensor([1]), num_classes=3).double()

tensor([[0., 1., 0.]], dtype=torch.float64)

In [52]:
criterion_f = CrossEntropyLoss()
criterion_f(torch.tensor([[0.05, 0.9, 0.05],[0.05, 0.2, 0.75]]).double(),
            F.one_hot(torch.tensor([1,0]), num_classes=3).double()
            )


tensor(1.0235, dtype=torch.float64)

In [53]:
F.one_hot(torch.tensor([1,0]), num_classes=3).double()

tensor([[0., 1., 0.],
        [1., 0., 0.]], dtype=torch.float64)

In [54]:
from torch.nn import MSELoss

In [56]:
import numpy as np
y_hat = np.array(10)
y = np.array(1)

In [57]:
y_hat

array(10)

In [59]:
mse_numpy = np.mean((y_hat - y ) **2)

In [60]:
mse_numpy

np.float64(81.0)

In [61]:
criterion = nn.MSELoss()

In [68]:
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)

In [70]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(7.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

tensor(1.)


In [71]:
leaky_relu_f = nn.LeakyReLU(0.05)
x = torch.tensor(-3.0, requires_grad=True)
leaky_relu_f(x)

tensor(-0.1500, grad_fn=<LeakyReluBackward0>)

In [72]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])
input_tensor.shape

torch.Size([1, 8])

In [73]:
def calculate_capacity(model):
  total = 0
  for p in model.parameters():
    total += p.numel()
  return total

In [74]:
model = nn.Sequential(
    nn.Linear(8,6),
    nn.Linear(6,4),
    nn.Linear(4,2)
)

In [75]:
calculate_capacity(model)

92

In [76]:
# from torch import optim
# sgd = optim.SGD(model.parameters(), lr = 0.001, momentum=0.8 )

In [77]:
model

Sequential(
  (0): Linear(in_features=8, out_features=6, bias=True)
  (1): Linear(in_features=6, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

In [83]:
for name, param in model.named_parameters():
    print(name), print(param)

0.weight
Parameter containing:
tensor([[ 0.0460,  0.1114, -0.2693,  0.0897, -0.0772, -0.3027,  0.0037, -0.1912],
        [ 0.3209, -0.1717, -0.3121, -0.0986,  0.2789, -0.2784, -0.0918,  0.2679],
        [ 0.1033,  0.1822, -0.0648,  0.0175,  0.1738, -0.0465,  0.1834,  0.2929],
        [-0.2327, -0.2373,  0.1222, -0.0887,  0.0372, -0.3104, -0.2609,  0.2232],
        [-0.0429,  0.1080,  0.0915,  0.0673, -0.0891,  0.2658, -0.1893, -0.1654],
        [-0.2056,  0.1693,  0.1753,  0.0280,  0.2190, -0.1665, -0.3387, -0.0766]],
       requires_grad=True)
0.bias
Parameter containing:
tensor([-0.1420, -0.0062,  0.2255, -0.3172, -0.0550, -0.3062],
       requires_grad=True)
1.weight
Parameter containing:
tensor([[ 0.2550, -0.1559,  0.1498, -0.1741, -0.2285,  0.0246],
        [-0.2753,  0.2412, -0.2306, -0.1217, -0.0057, -0.1375],
        [-0.2124,  0.2943, -0.3346, -0.0555, -0.2936, -0.1610],
        [ 0.0565, -0.2192,  0.3321,  0.2900, -0.1929, -0.1383]],
       requires_grad=True)
1.bias
Paramete

In [84]:
from torch.utils.data import TensorDataset, DataLoader

In [85]:
import numpy as np
import torch
from torch.utils.data import TensorDataset

np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

In [87]:
torch.tensor(np_features).float()

tensor([[0.9908, 0.4087, 0.9013, 0.5355, 0.0399, 0.1439, 0.7481, 0.8355],
        [0.4819, 0.1283, 0.7287, 0.3254, 0.9849, 0.2512, 0.7468, 0.8706],
        [0.9378, 0.0243, 0.5739, 0.4759, 0.3793, 0.2217, 0.2917, 0.3785],
        [0.7264, 0.3134, 0.8726, 0.6201, 0.7762, 0.8052, 0.4158, 0.4904],
        [0.6746, 0.5491, 0.9596, 0.7568, 0.6244, 0.6428, 0.2877, 0.8996],
        [0.3097, 0.7690, 0.4474, 0.5128, 0.7086, 0.1837, 0.0164, 0.0251],
        [0.1591, 0.8486, 0.6381, 0.3451, 0.3431, 0.1873, 0.2347, 0.4241],
        [0.3818, 0.1429, 0.5573, 0.8663, 0.1005, 0.7340, 0.5185, 0.4593],
        [0.6660, 0.9144, 0.2347, 0.8498, 0.1465, 0.9975, 0.8546, 0.5181],
        [0.8778, 0.5259, 0.9375, 0.6714, 0.2174, 0.4025, 0.6512, 0.8759],
        [0.4838, 0.0045, 0.9205, 0.1292, 0.9412, 0.8514, 0.7038, 0.5371],
        [0.9020, 0.2209, 0.2382, 0.8986, 0.9857, 0.9446, 0.1700, 0.2866]])

In [96]:
import pandas as pd

df = pd.DataFrame({
    'a': np.random.randn(10),
    'b': np.random.randn(10),
    'c': np.random.randn(10),
    'd': np.random.randn(10)
})

In [97]:
df.head()

a         b         c         d
0 -0.479721  0.094709  1.682762  0.350218
1  2.405675  1.328841 -0.254422  1.337986
2 -0.298308  1.985917 -0.307585 -0.877395
3 -1.179879 -0.530465  0.125694 -2.168660
4 -0.211021 -0.303478  1.814165  0.972989

In [102]:
torch.tensor(df.loc[:,['a','d']].to_numpy()).float()

tensor([[-0.4797,  0.3502],
        [ 2.4057,  1.3380],
        [-0.2983, -0.8774],
        [-1.1799, -2.1687],
        [-0.2110,  0.9730],
        [-3.5545, -1.4414],
        [-0.1188,  1.8350],
        [-1.6651, -1.5237],
        [-0.5101,  0.3468],
        [ 0.7559,  0.1311]])

In [105]:
import torchmetrics

/Users/sayan/personal/sayan_github/dl-lecture-notes/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [106]:
import torch
from transformers import BertModel

# Load pre-trained BERT model
model = BertModel.from_pretrained('bert-base-uncased')

# Print the model architecture
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [109]:
torch.tensor(df.loc[:,['a','d']].to_numpy()).shape[]0

torch.Size([10, 2])

In [ ]:
from torch.utils.data import DataLoader

In [111]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # Define the three linear layers
        self.fc1 = nn.Linear(9,16)
        self.fc2 = nn.Linear(16,8)
        self.fc3 = nn.Linear(8,1)
        
    def forward(self, x):
        # Pass x through linear layers adding activations
        x = nn.functional.relu(self.fc1(x))
        x = nn.functional.relu(self.fc2(x))
        x = nn.functional.sigmoid(self.fc2(x))
        return x

net = Net()

In [115]:
from torch.utils.data import TensorDataset, DataLoader
np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

np_dataset = TensorDataset(torch.tensor(np_features), torch.tensor(np_target))
tranining_dataset = DataLoader(np_dataset, shuffle=True, batch_size=3)

In [120]:
#next(iter(tranining_dataset))
for epoch in range(3):
    print(f"Epoch: {epoch}")
    for train_data, target_data in tranining_dataset:
        print(f"Got target: {target_data}")

Epoch: 0
Got target: tensor([[0.6252],
        [0.6334],
        [0.8998]], dtype=torch.float64)
Got target: tensor([[0.2375],
        [0.8709],
        [0.1204]], dtype=torch.float64)
Got target: tensor([[0.6478],
        [0.4696],
        [0.3876]], dtype=torch.float64)
Got target: tensor([[0.2197],
        [0.6333],
        [0.1496]], dtype=torch.float64)
Epoch: 1
Got target: tensor([[0.2197],
        [0.2375],
        [0.1496]], dtype=torch.float64)
Got target: tensor([[0.8709],
        [0.6333],
        [0.6478]], dtype=torch.float64)
Got target: tensor([[0.6252],
        [0.8998],
        [0.6334]], dtype=torch.float64)
Got target: tensor([[0.4696],
        [0.3876],
        [0.1204]], dtype=torch.float64)
Epoch: 2
Got target: tensor([[0.8709],
        [0.4696],
        [0.6478]], dtype=torch.float64)
Got target: tensor([[0.8998],
        [0.1496],
        [0.6252]], dtype=torch.float64)
Got target: tensor([[0.6334],
        [0.1204],
        [0.3876]], dtype=torch.float64)
Got t